# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11m9dg-Ytf5KLZxRrUtcG4wZ6nEa8wjlH
"""

!pip install opencv-python opencv-python-headless

!pip install opencv-python-headless==4.5.5.62

from google.colab import files
uploaded = files.upload()  # This will prompt you to upload the file

import cv2
import numpy as np
from google.colab import files

# Upload the video file
uploaded = files.upload()

# Get the name of the uploaded video file
video_file = list(uploaded.keys())[0]

# Load the video
cap = cv2.VideoCapture(video_file)

# Get video properties
frame_width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
frame_height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = int(cap.get(cv2.CAP_PROP_FPS))

# Initialize VideoWriter
output_file = 'dense_optical_flow_output.mp4'
out = cv2.VideoWriter(output_file, cv2.VideoWriter_fourcc(*'mp4v'), fps, (frame_width, frame_height))

# Read the first frame and convert it to grayscale
ret, first_frame = cap.read()
prev_gray = cv2.cvtColor(first_frame, cv2.COLOR_BGR2GRAY)

while cap.isOpened():
    ret, frame = cap.read()
    if not ret:
        break

    # Convert the current frame to grayscale
    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

    # Calculate dense optical flow using Farneback method
    flow = cv2.calcOpticalFlowFarneback(prev_gray, gray, None, 0.5, 3, 15, 3, 5, 1.2, 0)

    # Visualize optical flow
    magnitude, angle = cv2.cartToPolar(flow[..., 0], flow[..., 1])
    mask = np.zeros_like(frame)
    mask[..., 1] = 255
    mask[..., 0] = angle * 180 / np.pi / 2
    mask[..., 2] = cv2.normalize(magnitude, None, 0, 255, cv2.NORM_MINMAX)
    rgb = cv2.cvtColor(mask, cv2.COLOR_HSV2BGR)

    # Write the frame to the output video
    out.write(rgb)

    # Update the previous frame
    prev_gray = gray

# Release the video capture and writer objects
cap.release()
out.release()

# Download the output video file
files.download(output_file)  # This will prompt the download of the output video